name: docker

env:
  DOCKERHUB_USERNAME: erictik
  TAG: erictik/${{ github.event.repository.name }}:1.1.${{ github.run_number }}
  LATEST_TAG: erictik/${{ github.event.repository.name }}:latest
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"
#    paths:
#      - "**.ts"

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAG }},${{ env.LATEST_TAG }}
